---
title: "Tutorial 8"
format: html
editor: visual
---

```{r Load the lib}
library(tidyverse)
```

```{r Load the data}
data_tutorial <- read.csv("Data_Tables_Criminal_Incidents_Visualisation_Year_Ending_December_2019.csv")
```

```{r}
data_tutorial[,'Incidents.Recorded'] <- gsub(",","",data_tutorial[,'Incidents.Recorded'])
data_tutorial$Incidents.Recorded <- as.numeric(data_tutorial$Incidents.Recorded)
data_tutorial$Year <- as.Date(as.character(data_tutorial$Year), format="%Y")
```

```{r}
#| label: fig-A11
#| fig-cap: "Incidents record rate in the A11 Murder subgroup"
data_tutorial |> 
  filter(Offence.Subgroup == "A11 Murder") |> 
  ggplot(aes(y = Incidents.Recorded, x = Year)) +
  geom_point()
```

The incident rate that have been recorded for A11 Murder subgroup have been increasing through out the decade.

```{r}
data_tutorial$Incidents.Recorded <- str_remove(data_tutorial$Incidents.Recorded, ",")
data_tutorial %>% 
  group_by(Offence.Division) %>%
  summarise(Total = sum(as.numeric(Incidents.Recorded)), .groups = "drop") %>%
  arrange(desc(Total)) %>%
  ggplot(aes(x = Offence.Division, y = Total)) +
  geom_col() +
  coord_flip() +
  labs(title = "Total number of incidents for each Offence subdivision",
       x = "Offence subdivision",
       y = "Total number of incidents")
```


```{r}
data_tutorial$Incidents.Recorded <- str_remove(data_tutorial$Incidents.Recorded, pattern = ",")  
data_tutorial %>%
  mutate(Incidents.Recorded = as.numeric(Incidents.Recorded)) %>%
  filter(Offence.Division == "A Crimes against the person") %>% 
  ggplot(aes(x = as.factor(Offence.Subdivision), 
         y = Incidents.Recorded)) + 
  geom_col(width = 0.5) + 
  theme(axis.title.x = element_text(size = 10)) +
  coord_flip()
```



